title: 朝阳十班
page-top-title: 心之所向 素履以往 朝阳十班 逐梦争先
top-section-bg-text: 朝阳十班
home-subtitle: 朝阳十班&ensp;|&ensp;Class 10
copyright-text: '&copy; Dundunfu and Class10-hexing  2023-2025. All Rights Reserved.'
